[package]
name = "httpserver"
version = "0.1.0"
authors = ["dxps <marius.ileana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
