[package]
name = "httpserver"
version = "0.1.0"
authors = ["dxps <marius.ileana@gmail.com>"]
edition = "2018"

[dependencies]

http = { path = "../http" }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
